<?php

/**
 * Implements hook_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
 * @param type $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 */
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hello module.
    case 'help.page.hello':
      return '<p>' . t('Hello is a test module. :)') . '</p>';
  }
}

/**
 * Implements hook_cron()
 */
function hello_cron() {
  drupal_set_message(t('Error from Hello module! :P'), 'error');
}

/**
 * Implements hook_user_login()
 * @param AccountInformation $account
 */
function hello_user_login($account) {
  drupal_set_message(t('Hello dear @username ! :P', array('@username' => $account->getAccountName())), 'error');
}

function hello_node_update(Drupal\node\Entity\Node $entity) {
  $database = \Drupal::database();

  $database
      ->insert('hello_node_history')
      ->fields(array(
        'nid' => $entity->id(),
        'update_time' => $entity->getRevisionCreationTime(),
        'uid' => $entity->getRevisionAuthor()->id()
      ))
      ->execute();
}

/**
 * Implements module_page_attachments_alter()
 * @param array $attachments
 */
function hello_page_attachments_alter(array &$attachments) {
  $attachments['#attached']['library'][] = 'hello/base';
}

function hello_preprocess_block(array &$variables) {
  $variables['attributes']['class'][] = \Drupal::config('hello.config')->get('color');
}
