<?php

/**
 * @file
 * Contains abcdef.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function abcdef_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the abcdef module.
    case 'help.page.abcdef':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function abcdef_theme() {
  return [
    'abcdef' => [
      'template' => 'abcdef',
      'render element' => 'children',
    ],
  ];
}
